name: Preprocessing Workflow

on:
  push:
    paths:
      - 'preprocessing/**'
      - 'recruitment_data_raw.csv'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing script
        working-directory: preprocessing
        run: |
          python automate_Wulandari.py

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add preprocessing/recruitment_data_clean.csv
          git commit -m "Update preprocessed dataset" || echo "No changes"
          git push
